### ISSUE TITLE
Bug in parsing for some multi-page Documents,

### ISSUE THREAD

**Issue by tshrjn** [mludvig/amazon-textract-parser#1]
When parsing some multi-page outputs, there's a bug in the `trp.py` file.
Due to which the keys in the `blockmap` at line [142](https://github.com/mludvig/amazon-textract-parser/blob/master/trp/__init__.py#L142) is not found & `KeyError Exception` is thrown.

PS: Also, put an [issue](https://github.com/aws-samples/amazon-textract-code-samples/issues/9) in the AWS Samples file there.

Full Traceback if needed is here:

```
Traceback (most recent call last):
  File "textract_kv.py", line 72, in <module>
    lines_to_file(resp_to_keyValues(response), fp)
  File "/path/to/proj/resp_parser.py", line 28, in resp_to_keyValues
    doc = Document(response)
  File "/path/to/user/.pyenv/versions/anaconda3-2019.03/envs/textract/lib/python3.7/site-packages/trp/__init__.py", line 633, in __init__
    self._parse()
  File "/path/to/user/.pyenv/versions/anaconda3-2019.03/envs/textract/lib/python3.7/site-packages/trp/__init__.py", line 667, in _parse
    page = Page(documentPage["Blocks"], self._blockMap)
  File "/path/to/user/.pyenv/versions/anaconda3-2019.03/envs/textract/lib/python3.7/site-packages/trp/__init__.py", line 516, in __init__
    self._parse(blockMap)
  File "/path/to/user/.pyenv/versions/anaconda3-2019.03/envs/textract/lib/python3.7/site-packages/trp/__init__.py", line 530, in _parse
    l = Line(item, blockMap)
  File "/path/to/user/.pyenv/versions/anaconda3-2019.03/envs/textract/lib/python3.7/site-packages/trp/__init__.py", line 142, in __init__
    if(blockMap[cid]["BlockType"] == "WORD"):
KeyError: '2a50d992-0aa4-4cda-8c87-0b88e8dccab9'

```

**Comment by 93arnaldo** [comment]
I'm having the exact same issue while parsing a multi-page pdf.

Tradeback:
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-14-a0bef17847c4> in <module>()
----> 1 doc = Document(response)
      2 pages_list = []
      3 for index, page in enumerate(doc.pages):
      4     form_dict = {}
      5     for field in page.form.fields:

/usr/local/lib/python3.6/dist-packages/trp/__init__.py in __init__(self, responsePages)
    631         self._pages = []
    632 
--> 633         self._parse()
    634 
    635     def __str__(self):

/usr/local/lib/python3.6/dist-packages/trp/__init__.py in _parse(self)
    665         self._responseDocumentPages, self._blockMap = self._parseDocumentPagesAndBlockMap()
    666         for documentPage in self._responseDocumentPages:
--> 667             page = Page(documentPage["Blocks"], self._blockMap)
    668             self._pages.append(page)
    669 

/usr/local/lib/python3.6/dist-packages/trp/__init__.py in __init__(self, blocks, blockMap)
    514         self._content = []
    515 
--> 516         self._parse(blockMap)
    517 
    518     def __str__(self):

/usr/local/lib/python3.6/dist-packages/trp/__init__.py in _parse(self, blockMap)
    528                 self._id = item['Id']
    529             elif item["BlockType"] == "LINE":
--> 530                 l = Line(item, blockMap)
    531                 self._lines.append(l)
    532                 self._content.append(l)

/usr/local/lib/python3.6/dist-packages/trp/__init__.py in __init__(self, block, blockMap)
    140                 if(rs['Type'] == 'CHILD'):
    141                     for cid in rs['Ids']:
--> 142                         if(blockMap[cid]["BlockType"] == "WORD"):
    143                             self._words.append(Word(blockMap[cid], blockMap))
    144     def __str__(self):

KeyError: 'f8a0fef2-4c76-472c-aaad-5893388d6779'
```

**Comment by mludvig** [comment]
Can you save the output of `analyze_document()` to a JSON file and attach it here? Thanks!

**Comment by 93arnaldo** [comment]
Hi @mludvig, thanks for your prompt answer! Just when you commented I was in the path to solve it and I believe it's solved now. 
Also, I didn't share the output of `analyze_document()` as requested because it is private information.

As mentioned [here](https://github.com/aws-samples/amazon-textract-response-parser/issues/6#issuecomment-682113847), it's not a bug, although the error message should be more explanatory. 

What happens is that when Document() is trying to map and parse the blocks by matching the blockIds to get all the key-value pairs, there are blockIds that it can't find. This is caused because the function [get_document_analysis](https://docs.aws.amazon.com/textract/latest/dg/textract-dg.pdf#how-it-works-analyzing), has a MaxResults parameter that limits the response blocks to 1000. As commented [here](https://github.com/aws-samples/amazon-textract-response-parser/issues/6#issuecomment-682113847) by @josephmisiti, the solution is to use NextToken with get_document_analysis again to get the next set of 1000 blocks. 

How I solve it though, was without using tpr.Document(). I solve it with a modification of the [code from Kashif Imran](https://aws.amazon.com/blogs/machine-learning/automatically-extract-text-and-structured-data-from-documents-with-amazon-textract/) (look for **PDF document processing (async API operations)** in the blog)

This is my solution

```python
response = textract.get_document_analysis(JobId=text_analysis['JobId'])

while response['JobStatus'] == 'IN_PROGRESS':
    sleep(5)
    response = textract.get_document_analysis(JobId=text_analysis['JobId'])

responses_list = []
responses_list.append(response)

nextToken = None
if('NextToken' in response):
    nextToken = response['NextToken']

while(nextToken):
    response = textract.get_document_analysis(JobId=text_analysis['JobId'], NextToken=nextToken)
    responses_list.append(response)
    nextToken = None
    if('NextToken' in response):
        nextToken = response['NextToken']


## From here is were the modifications start
def find_value_block(key_block, value_map):
    for relationship in key_block['Relationships']:
        if relationship['Type'] == 'VALUE':
            for value_id in relationship['Ids']:
                value_block = value_map[value_id]
    return value_block

def get_text(result, blocks_map):
    text = ''
    if 'Relationships' in result:
        for relationship in result['Relationships']:
            if relationship['Type'] == 'CHILD':
                for child_id in relationship['Ids']:
                    word = blocks_map[child_id]
                    if word['BlockType'] == 'WORD':
                        text += word['Text'] + ' '
                    if word['BlockType'] == 'SELECTION_ELEMENT':
                        if word['SelectionStatus'] == 'SELECTED':
                            text += 'X '                    
    return text

kvs = {}
key_map = {}
value_map = {}
block_map = {}
for response_dict in responses_list:
    for block in response_dict['Blocks']:
        block_id = block['Id']   
        block_page = block['Page']
        block_map[block_id] = block
        if block['BlockType'] == 'KEY_VALUE_SET':
            if 'KEY' in block['EntityTypes']:
                key_map[block_id] = [block, block_page]
            else:
                value_map[block_id] = block

for block_id, key_block in key_map.items():
    value_block = find_value_block(key_block[0], value_map)
    key = get_text(key_block[0], block_map)
    val = get_text(value_block, block_map)
# For me it was very important to track the pages where the key value pairs were.
# The solution I found was to store the page as a value of the `key_map` dictionary and 
# using it as a prefix for the each key of `kvs` for later use
    kvs[f'Page{key_block[1]:04}_{key}'] = val
```

I believe that a modification of this could be implemented in the tpr module @darwaishx.
That way when looking for key-value-pairs with netxtoken, the Document() parse doesn't break


Hope it helps :)

**Comment by lie-nielsen** [comment]
Maybe you could:
```
    mega_response = client.get_document_analysis(
        JobId=job
    )

    nextToken = None
    if('NextToken' in mega_response):
        nextToken = mega_response['NextToken']
    while(nextToken):
        response = client.get_document_analysis(JobId=job, NextToken=nextToken)
        mega_response['Blocks'].extend(response['Blocks'])
        nextToken = None
        if('NextToken' in response):
            nextToken = response['NextToken']
    doc = trp.Document(mega_response)
```

**Comment by schadem** [comment]
I added a package and method to call Textract which also works for paginated output. https://github.com/aws-samples/amazon-textract-textractor/tree/master/caller
Just use call_textract from that and you'll be good.

**Comment by Aleceler** [comment]
> Maybe you could:
> 
> ```
>     mega_response = client.get_document_analysis(
>         JobId=job
>     )
> 
>     nextToken = None
>     if('NextToken' in mega_response):
>         nextToken = mega_response['NextToken']
>     while(nextToken):
>         response = client.get_document_analysis(JobId=job, NextToken=nextToken)
>         mega_response['Blocks'].extend(response['Blocks'])
>         nextToken = None
>         if('NextToken' in response):
>             nextToken = response['NextToken']
>     doc = trp.Document(mega_response)
> ```

Ty, this works well,
after this:

doc = trp.Document(mega_response)

    detectedText = {}
            
    for page in doc.pages:
        for field in page.form.fields:
            if field.value:
                detectedText[field.key.text] = field.value.text
            else:
                detectedText[field.key.text] = ""

and you get same json of aws ui
